# src/main/resources/application.yml
spring:
  application:
    name: workflow-management-system
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME:workflow}
    password: ${DB_PASSWORD:password}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  data:
    jdbc:
      dialect: oracle
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    ac.wf2: DEBUG
    org.springframework.cache: DEBUG
    org.redisson: INFO

workflow:
  config:
    folder: ${WORKFLOW_CONFIG_FOLDER:./config/workflows}
    scan-interval: 60000 # 1 minute
  execution:
    max-concurrent-workflows: 10
    task-timeout: 300000 # 5 minutes
  cache:
    running-workflows-ttl: 3600 # 1 hour
    completed-workflows-ttl: 86400 # 24 hours
  notification:
    enabled: true
    async: true

redisson:
  address: redis://localhost:6379
  database: 0
  connection-pool-size: 64
  connection-minimum-idle-size: 10
  timeout: 3000
  retry-attempts: 3
  retry-interval: 1500